groups:
  - name: FuelPriceAlerts
    rules:
      - alert: FuelPriceSpike
        expr: fuel_price > 130
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Fuel price too high"
          description: "Fuel price exceeded â‚¹130 in one or more cities"

